server:
  port: 9001

security:
  cas:
    server: http://localhost:8080/sso
    client: http://localhost:9001
    disable: false
#    ignore: /v0.1/user/**

spring:
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/liuran?useUnicode=true&amp;characterEncoding=UTF-8&serverTimezone=CST
      username: root
      password: liuran
      driver-class-name: com.mysql.jdbc.Driver