spring:
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/liuran?useUnicode=true&amp;characterEncoding=UTF-8&serverTimezone=CST
      username: root
      password: liuran
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:resources/mybatis/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.winter.model